# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 396eda0c3841a01c9125538861f04c118dc6325d53a6ccf54443ccacc31b84df7bad3865247fbfb38e6f890786ee825e219cd5230e16e65819d3e6bf9d3930b8

test:
  secret_key_base: 63fc70eda2d4b02cd45fd7a53223ec3a7cb70bc35843af58ce81eb9862d6afc89df12a6cbcc2e78306835debfb7b0ee18f00e73b6419ce8a04d1a6030bbb70ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
